### ISSUE TITLE
Fix DeprecationWarning

### ISSUE THREAD

**Issue by nailgun** [smpio/kubernator-vscode#1]
```
(node:53484) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
```

**Comment by nailgun** [comment]
Stack trace:

```
(node:23520) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:194:11)
    at new Buffer (buffer.js:281:3)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/ftp/lib/connection.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/get-uri/dist/ftp.js:16:31)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/get-uri/dist/index.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:17:35)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:40:30)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at r.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1722)
    at r.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:10249)
    at l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:6145)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:6:1702)
    at _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2556)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:56953)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31872)
    at r._createAndEvalScript (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2600)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:2239
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:131:14)
```

**Comment by nailgun** [comment]
Seems like doesn't related to the extension, but to extension host
